experienceKenya/config/routes.rb
Rails.application.routes.draw do
	root 'home#index'
  get 'home/index'

  resources :sites
  resources :hotels
  resources :counties
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

experienceKenya/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

experienceKenya/app/models/county.rb
class County < ApplicationRecord
	has_one :place;
end

experienceKenya/app/models/hotel.rb
class Hotel < ApplicationRecord
	belongs_to :place
end

experienceKenya/app/models/place.rb
class Place < ApplicationRecord
  belongs_to :county
end

experienceKenya/app/models/site.rb
class Site < ApplicationRecord
	belongs_to :place
end

experienceKenya/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

experienceKenya/app/controllers/counties_controller.rb
class CountiesController < ApplicationController
  before_action :set_county, only: [:show, :edit, :update, :destroy]

  # GET /counties
  # GET /counties.json
  def index
    @counties = County.all
  end

  # GET /counties/1
  # GET /counties/1.json
  def show
  end

  # GET /counties/new
  def new
    @county = County.new
  end

  # GET /counties/1/edit
  def edit
  end

  # POST /counties
  # POST /counties.json
  def create
    @county = County.new(county_params)

    respond_to do |format|
      if @county.save
        format.html { redirect_to @county, notice: 'County was successfully created.' }
        format.json { render :show, status: :created, location: @county }
      else
        format.html { render :new }
        format.json { render json: @county.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /counties/1
  # PATCH/PUT /counties/1.json
  def update
    respond_to do |format|
      if @county.update(county_params)
        format.html { redirect_to @county, notice: 'County was successfully updated.' }
        format.json { render :show, status: :ok, location: @county }
      else
        format.html { render :edit }
        format.json { render json: @county.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /counties/1
  # DELETE /counties/1.json
  def destroy
    @county.destroy
    respond_to do |format|
      format.html { redirect_to counties_url, notice: 'County was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_county
      @county = County.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def county_params
      params.require(:county).permit(:name, :description)
    end
end

experienceKenya/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

experienceKenya/app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
  before_action :set_hotel, only: [:show, :edit, :update, :destroy]

  # GET /hotels
  # GET /hotels.json
  def index
    @hotels = Hotel.all
  end

  # GET /hotels/1
  # GET /hotels/1.json
  def show
  end

  # GET /hotels/new
  def new
    @hotel = Hotel.new
  end

  # GET /hotels/1/edit
  def edit
  end

  # POST /hotels
  # POST /hotels.json
  def create
    @hotel = Hotel.new(hotel_params)

    respond_to do |format|
      if @hotel.save
        format.html { redirect_to @hotel, notice: 'Hotel was successfully created.' }
        format.json { render :show, status: :created, location: @hotel }
      else
        format.html { render :new }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hotels/1
  # PATCH/PUT /hotels/1.json
  def update
    respond_to do |format|
      if @hotel.update(hotel_params)
        format.html { redirect_to @hotel, notice: 'Hotel was successfully updated.' }
        format.json { render :show, status: :ok, location: @hotel }
      else
        format.html { render :edit }
        format.json { render json: @hotel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hotels/1
  # DELETE /hotels/1.json
  def destroy
    @hotel.destroy
    respond_to do |format|
      format.html { redirect_to hotels_url, notice: 'Hotel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hotel
      @hotel = Hotel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hotel_params
      params.require(:hotel).permit(:name, :description, :rating, :image, :place)
    end
end

experienceKenya/app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: [:show, :edit, :update, :destroy]

  # GET /sites
  # GET /sites.json
  def index
    @sites = Site.all
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params)

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url, notice: 'Site was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:name, :description, :rating, :image, :place)
    end
end

experienceKenya/app/helpers/application_helper.rb
module ApplicationHelper
end

experienceKenya/app/helpers/counties_helper.rb
module CountiesHelper
end

experienceKenya/app/helpers/home_helper.rb
module HomeHelper
end

experienceKenya/app/helpers/hotels_helper.rb
module HotelsHelper
end

experienceKenya/app/helpers/sites_helper.rb
module SitesHelper
end

experienceKenya/app/views/counties/_form.html.erb
<%= form_for(county) do |f| %>
  <% if county.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(county.errors.count, "error") %> prohibited this county from being saved:</h2>

      <ul>
      <% county.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

experienceKenya/app/views/counties/edit.html.erb
<h1>Editing County</h1>

<%= render 'form', county: @county %>

<%= link_to 'Show', @county %> |
<%= link_to 'Back', counties_path %>

experienceKenya/app/views/counties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Counties</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @counties.each do |county| %>
      <tr>
        <td><%= county.name %></td>
        <td><%= county.description %></td>
        <td><%= link_to 'Show', county %></td>
        <td><%= link_to 'Edit', edit_county_path(county) %></td>
        <td><%= link_to 'Destroy', county, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New County', new_county_path %>

experienceKenya/app/views/counties/new.html.erb
<h1>New County</h1>

<%= render 'form', county: @county %>

<%= link_to 'Back', counties_path %>

experienceKenya/app/views/counties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @county.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @county.description %>
</p>

<%= link_to 'Edit', edit_county_path(@county) %> |
<%= link_to 'Back', counties_path %>

experienceKenya/app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body class="container">
<div  class="contactUs pull-right">
<a href="#">Contact Us</a>
	
</div>
<div class="  banner hidden-md">
</div>
<nav id= "header-nav" class="navbar navbar-default">
<div class="container">
<div class="navbar-header">

             <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapsable-nav" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

</div>
<div id ="collapsable-nav" class=" collapse navbar-collapse pull-right">
  <ul id="nav-list" class="nav navbar-nav navbar-left">
  <li>
  <a href="#">Home</a>

  </li>
  <li>
  <a href="#projects">About us</a>

  </li>
  <li>
  <a href="#contact">Careers</a>

  </li>
  <li>
  <a href="#contact">Contacts</a>

  </li>

  </ul>
</div>


        </div>

        </nav><!-- end of nav bar
 -->
<div class="row" id="main-body">
<div class= "col-md-6 col-lg-6 col-sm-12" id="countyList">
<div class="containerHolder">
	
</div>
	
</div>

<div class= "col-md-6 col-lg-6 col-sm-12" id="whatToDo">
	
</div>
	
</div>

</body>
</html>


	

experienceKenya/app/views/hotels/_form.html.erb
<%= form_for(hotel) do |f| %>
  <% if hotel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(hotel.errors.count, "error") %> prohibited this hotel from being saved:</h2>

      <ul>
      <% hotel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :rating %>
    <%= f.number_field :rating %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="field">
    <%= f.label :place %>
    <%= f.text_field :place %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

experienceKenya/app/views/hotels/edit.html.erb
<h1>Editing Hotel</h1>

<%= render 'form', hotel: @hotel %>

<%= link_to 'Show', @hotel %> |
<%= link_to 'Back', hotels_path %>

experienceKenya/app/views/hotels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Hotels</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Rating</th>
      <th>Image</th>
      <th>Place</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hotels.each do |hotel| %>
      <tr>
        <td><%= hotel.name %></td>
        <td><%= hotel.description %></td>
        <td><%= hotel.rating %></td>
        <td><%= hotel.image %></td>
        <td><%= hotel.place %></td>
        <td><%= link_to 'Show', hotel %></td>
        <td><%= link_to 'Edit', edit_hotel_path(hotel) %></td>
        <td><%= link_to 'Destroy', hotel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hotel', new_hotel_path %>

experienceKenya/app/views/hotels/new.html.erb
<h1>New Hotel</h1>

<%= render 'form', hotel: @hotel %>

<%= link_to 'Back', hotels_path %>

experienceKenya/app/views/hotels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @hotel.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @hotel.description %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @hotel.rating %>
</p>

<p>
  <strong>Image:</strong>
  <%= @hotel.image %>
</p>

<p>
  <strong>Place:</strong>
  <%= @hotel.place %>
</p>

<%= link_to 'Edit', edit_hotel_path(@hotel) %> |
<%= link_to 'Back', hotels_path %>

experienceKenya/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExperienceKenya</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

experienceKenya/app/views/sites/_form.html.erb
<%= form_for(site) do |f| %>
  <% if site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% site.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :rating %>
    <%= f.number_field :rating %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="field">
    <%= f.label :place %>
    <%= f.text_field :place %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

experienceKenya/app/views/sites/edit.html.erb
<h1>Editing Site</h1>

<%= render 'form', site: @site %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

experienceKenya/app/views/sites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sites</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Rating</th>
      <th>Image</th>
      <th>Place</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sites.each do |site| %>
      <tr>
        <td><%= site.name %></td>
        <td><%= site.description %></td>
        <td><%= site.rating %></td>
        <td><%= site.image %></td>
        <td><%= site.place %></td>
        <td><%= link_to 'Show', site %></td>
        <td><%= link_to 'Edit', edit_site_path(site) %></td>
        <td><%= link_to 'Destroy', site, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Site', new_site_path %>

experienceKenya/app/views/sites/new.html.erb
<h1>New Site</h1>

<%= render 'form', site: @site %>

<%= link_to 'Back', sites_path %>

experienceKenya/app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @site.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @site.description %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @site.rating %>
</p>

<p>
  <strong>Image:</strong>
  <%= @site.image %>
</p>

<p>
  <strong>Place:</strong>
  <%= @site.place %>
</p>

<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', sites_path %>